### ISSUE TITLE
array<string> is not work

### ISSUE THREAD

**Issue by kubode** [kubode/swagger-codegen-kotlin#2]
```yaml
properties:
  foo:
    type: array
    items:
      type: string
```

```kotlin
val @SerializedName("foo") foo: List<string>, // **s**tring
```
